# Generated by Django 5.1.5 on 2025-03-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campustravel",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campustravel",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
