# Generated by Django 5.1.6 on 2025-03-17 15:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qrscan',
            unique_together={('user', 'scan_date', 'qr_code')},
        ),
    ]
