# Generated by Django 5.1.5 on 2025-03-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_longest_streak_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='profile_pics'),
        ),
    ]
